# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.AclTokenRoleLink do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Name
  ]

  @type t :: %__MODULE__{
          :ID => String.t() | nil,
          :Name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AclTokenRoleLink do
  def decode(value, _options) do
    value
  end
end
