# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AgentSelf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Config,
    :Member,
    :Stats
  ]

  @type t :: %__MODULE__{
          :Config => %{optional(String.t()) => map()} | nil,
          :Member => NomadClient.Model.AgentMember.t() | nil,
          :Stats => %{optional(String.t()) => %{optional(String.t()) => String.t()}} | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AgentSelf do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Member, :struct, NomadClient.Model.AgentMember, options)
  end
end
