# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AgentHealthResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Client,
    :Server
  ]

  @type t :: %__MODULE__{
          :Client => NomadClient.Model.AgentHealth.t() | nil,
          :Server => NomadClient.Model.AgentHealth.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AgentHealthResponse do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Client, :struct, NomadClient.Model.AgentHealth, options)
    |> deserialize(:Server, :struct, NomadClient.Model.AgentHealth, options)
  end
end
