# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AgentMember do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Addr,
    :Port,
    :Tags,
    :Status,
    :ProtocolMin,
    :ProtocolMax,
    :ProtocolCur,
    :DelegateMin,
    :DelegateMax,
    :DelegateCur
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :Addr => String.t() | nil,
          :Port => integer() | nil,
          :Tags => %{optional(String.t()) => String.t()} | nil,
          :Status => String.t() | nil,
          :ProtocolMin => integer() | nil,
          :ProtocolMax => integer() | nil,
          :ProtocolCur => integer() | nil,
          :DelegateMin => integer() | nil,
          :DelegateMax => integer() | nil,
          :DelegateCur => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AgentMember do
  def decode(value, _options) do
    value
  end
end
