# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AllocatedTaskResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CPU,
    :Memory,
    :Networks
  ]

  @type t :: %__MODULE__{
          :CPU => NomadClient.Model.AllocatedCpuResources.t() | nil,
          :Memory => NomadClient.Model.AllocatedMemoryResources.t() | nil,
          :Networks => [NomadClient.Model.NetworkResource.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AllocatedTaskResources do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:CPU, :struct, NomadClient.Model.AllocatedCpuResources, options)
    |> deserialize(:Memory, :struct, NomadClient.Model.AllocatedMemoryResources, options)
    |> deserialize(:Networks, :list, NomadClient.Model.NetworkResource, options)
  end
end
