# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.AllocatedDeviceResource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DeviceIDs,
    :Name,
    :Type,
    :Vendor
  ]

  @type t :: %__MODULE__{
          :DeviceIDs => [String.t()] | nil,
          :Name => String.t() | nil,
          :Type => String.t() | nil,
          :Vendor => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AllocatedDeviceResource do
  def decode(value, _options) do
    value
  end
end
