# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AllocFileInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :IsDir,
    :Size,
    :FileMode,
    :ModTime,
    :ContentType
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :IsDir => boolean() | nil,
          :Size => integer() | nil,
          :FileMode => String.t() | nil,
          :ModTime => DateTime.t() | nil,
          :ContentType => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AllocFileInfo do
  def decode(value, _options) do
    value
  end
end
