# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AllocatedResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Tasks,
    :Shared
  ]

  @type t :: %__MODULE__{
          :Tasks => %{optional(String.t()) => NomadClient.Model.AllocatedTaskResources.t()} | nil,
          :Shared => NomadClient.Model.AllocatedSharedResources.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AllocatedResources do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Tasks, :map, NomadClient.Model.AllocatedTaskResources, options)
    |> deserialize(:Shared, :struct, NomadClient.Model.AllocatedSharedResources, options)
  end
end
