# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.AllocatedResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Shared,
    :Tasks
  ]

  @type t :: %__MODULE__{
          :Shared => NomadClient.Model.AllocatedSharedResources.t() | nil,
          :Tasks => %{optional(String.t()) => NomadClient.Model.AllocatedTaskResources.t()} | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AllocatedResources do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Shared, :struct, NomadClient.Model.AllocatedSharedResources, options)
    |> deserialize(:Tasks, :map, NomadClient.Model.AllocatedTaskResources, options)
  end
end
