# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.AllocDeploymentStatus do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Healthy,
    :Timestamp,
    :Canary,
    :ModifyIndex
  ]

  @type t :: %__MODULE__{
          :Healthy => boolean() | nil,
          :Timestamp => DateTime.t() | nil,
          :Canary => boolean() | nil,
          :ModifyIndex => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.AllocDeploymentStatus do
  def decode(value, _options) do
    value
  end
end
