# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.Attribute do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Bool,
    :Float,
    :Int,
    :String,
    :Unit
  ]

  @type t :: %__MODULE__{
          :Bool => boolean() | nil,
          :Float => float() | nil,
          :Int => integer() | nil,
          :String => String.t() | nil,
          :Unit => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.Attribute do
  def decode(value, _options) do
    value
  end
end
