# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.ConsulGatewayTlsConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CipherSuites,
    :Enabled,
    :TLSMaxVersion,
    :TLSMinVersion
  ]

  @type t :: %__MODULE__{
          :CipherSuites => [String.t()] | nil,
          :Enabled => boolean() | nil,
          :TLSMaxVersion => String.t() | nil,
          :TLSMinVersion => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ConsulGatewayTlsConfig do
  def decode(value, _options) do
    value
  end
end
