# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.ConsulUpstream do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Datacenter,
    :DestinationName,
    :DestinationNamespace,
    :LocalBindAddress,
    :LocalBindPort,
    :MeshGateway
  ]

  @type t :: %__MODULE__{
          :Datacenter => String.t() | nil,
          :DestinationName => String.t() | nil,
          :DestinationNamespace => String.t() | nil,
          :LocalBindAddress => String.t() | nil,
          :LocalBindPort => integer() | nil,
          :MeshGateway => NomadClient.Model.ConsulMeshGateway.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ConsulUpstream do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:MeshGateway, :struct, NomadClient.Model.ConsulMeshGateway, options)
  end
end
