# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.ConsulTerminatingConfigEntry do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Services
  ]

  @type t :: %__MODULE__{
          :Services => [NomadClient.Model.ConsulLinkedService.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ConsulTerminatingConfigEntry do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Services, :list, NomadClient.Model.ConsulLinkedService, options)
  end
end
