# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.CpuStats do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :SystemMode,
    :UserMode,
    :TotalTicks,
    :ThrottledPeriods,
    :ThrottledTime,
    :Percent,
    :Measured
  ]

  @type t :: %__MODULE__{
          :SystemMode => float() | nil,
          :UserMode => float() | nil,
          :TotalTicks => float() | nil,
          :ThrottledPeriods => integer() | nil,
          :ThrottledTime => integer() | nil,
          :Percent => float() | nil,
          :Measured => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CpuStats do
  def decode(value, _options) do
    value
  end
end
