# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.CsiSnapshotCreateResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :KnownLeader,
    :LastContact,
    :LastIndex,
    :NextToken,
    :RequestTime,
    :Snapshots
  ]

  @type t :: %__MODULE__{
          :KnownLeader => boolean() | nil,
          :LastContact => integer() | nil,
          :LastIndex => integer() | nil,
          :NextToken => String.t() | nil,
          :RequestTime => integer() | nil,
          :Snapshots => [NomadClient.Model.CsiSnapshot.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiSnapshotCreateResponse do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Snapshots, :list, NomadClient.Model.CsiSnapshot, options)
  end
end
