# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.CsiTopology do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Segments
  ]

  @type t :: %__MODULE__{
          :Segments => %{optional(String.t()) => String.t()} | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiTopology do
  def decode(value, _options) do
    value
  end
end
