# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.CsiSnapshotCreateRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Namespace,
    :Region,
    :SecretID,
    :Snapshots
  ]

  @type t :: %__MODULE__{
          :Namespace => String.t() | nil,
          :Region => String.t() | nil,
          :SecretID => String.t() | nil,
          :Snapshots => [NomadClient.Model.CsiSnapshot.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiSnapshotCreateRequest do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Snapshots, :list, NomadClient.Model.CsiSnapshot, options)
  end
end
