# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.CsiControllerInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :SupportsAttachDetach,
    :SupportsClone,
    :SupportsCondition,
    :SupportsCreateDelete,
    :SupportsCreateDeleteSnapshot,
    :SupportsExpand,
    :SupportsGet,
    :SupportsGetCapacity,
    :SupportsListSnapshots,
    :SupportsListVolumes,
    :SupportsListVolumesAttachedNodes,
    :SupportsReadOnlyAttach
  ]

  @type t :: %__MODULE__{
          :SupportsAttachDetach => boolean() | nil,
          :SupportsClone => boolean() | nil,
          :SupportsCondition => boolean() | nil,
          :SupportsCreateDelete => boolean() | nil,
          :SupportsCreateDeleteSnapshot => boolean() | nil,
          :SupportsExpand => boolean() | nil,
          :SupportsGet => boolean() | nil,
          :SupportsGetCapacity => boolean() | nil,
          :SupportsListSnapshots => boolean() | nil,
          :SupportsListVolumes => boolean() | nil,
          :SupportsListVolumesAttachedNodes => boolean() | nil,
          :SupportsReadOnlyAttach => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiControllerInfo do
  def decode(value, _options) do
    value
  end
end
