# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.CsiNodeInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :MaxVolumes,
    :AccessibleTopology,
    :RequiresNodeStageVolume
  ]

  @type t :: %__MODULE__{
          :ID => String.t() | nil,
          :MaxVolumes => integer() | nil,
          :AccessibleTopology => NomadClient.Model.CsiTopology.t() | nil,
          :RequiresNodeStageVolume => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiNodeInfo do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:AccessibleTopology, :struct, NomadClient.Model.CsiTopology, options)
  end
end
