# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.CsiVolumeCapability do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :AccessMode,
    :AttachmentMode
  ]

  @type t :: %__MODULE__{
          :AccessMode => String.t() | nil,
          :AttachmentMode => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiVolumeCapability do
  def decode(value, _options) do
    value
  end
end
