# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.CsiSnapshot do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CreateTime,
    :ExternalSourceVolumeID,
    :ID,
    :IsReady,
    :Name,
    :Parameters,
    :PluginID,
    :Secrets,
    :SizeBytes,
    :SourceVolumeID
  ]

  @type t :: %__MODULE__{
          :CreateTime => integer() | nil,
          :ExternalSourceVolumeID => String.t() | nil,
          :ID => String.t() | nil,
          :IsReady => boolean() | nil,
          :Name => String.t() | nil,
          :Parameters => %{optional(String.t()) => String.t()} | nil,
          :PluginID => String.t() | nil,
          :Secrets => %{optional(String.t()) => String.t()} | nil,
          :SizeBytes => integer() | nil,
          :SourceVolumeID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.CsiSnapshot do
  def decode(value, _options) do
    value
  end
end
