# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DeploymentAllocHealthRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DeploymentID,
    :HealthyAllocationIDs,
    :UnhealthyAllocationIDs
  ]

  @type t :: %__MODULE__{
          :DeploymentID => String.t() | nil,
          :HealthyAllocationIDs => [String.t()] | nil,
          :UnhealthyAllocationIDs => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DeploymentAllocHealthRequest do
  def decode(value, _options) do
    value
  end
end
