# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DeploymentPromoteRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DeploymentID,
    :All,
    :Groups
  ]

  @type t :: %__MODULE__{
          :DeploymentID => String.t() | nil,
          :All => boolean() | nil,
          :Groups => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DeploymentPromoteRequest do
  def decode(value, _options) do
    value
  end
end
