# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DeploymentPauseRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DeploymentID,
    :Pause
  ]

  @type t :: %__MODULE__{
          :DeploymentID => String.t() | nil,
          :Pause => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DeploymentPauseRequest do
  def decode(value, _options) do
    value
  end
end
