# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DeploymentUpdateResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalID,
    :EvalCreateIndex,
    :DeploymentModifyIndex,
    :RevertedJobVersion
  ]

  @type t :: %__MODULE__{
          :EvalID => String.t() | nil,
          :EvalCreateIndex => integer() | nil,
          :DeploymentModifyIndex => integer() | nil,
          :RevertedJobVersion => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DeploymentUpdateResponse do
  def decode(value, _options) do
    value
  end
end
