# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.DesiredTransition do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Migrate,
    :Reschedule
  ]

  @type t :: %__MODULE__{
          :Migrate => boolean() | nil,
          :Reschedule => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DesiredTransition do
  def decode(value, _options) do
    value
  end
end
