# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DeviceGroupStats do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Vendor,
    :Type,
    :Name,
    :InstanceStats
  ]

  @type t :: %__MODULE__{
          :Vendor => String.t() | nil,
          :Type => String.t() | nil,
          :Name => String.t() | nil,
          :InstanceStats => %{optional(String.t()) => NomadClient.Model.DeviceStats.t()} | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DeviceGroupStats do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:InstanceStats, :map, NomadClient.Model.DeviceStats, options)
  end
end
