# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.DnsConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Options,
    :Searches,
    :Servers
  ]

  @type t :: %__MODULE__{
          :Options => [String.t()] | nil,
          :Searches => [String.t()] | nil,
          :Servers => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DnsConfig do
  def decode(value, _options) do
    value
  end
end
