# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DrainSpec do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Deadline,
    :IgnoreSystemJobs
  ]

  @type t :: %__MODULE__{
          :Deadline => integer(),
          :IgnoreSystemJobs => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DrainSpec do
  def decode(value, _options) do
    value
  end
end
