# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.DrainStrategy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DrainSpec,
    :ForceDeadline,
    :StartedAt
  ]

  @type t :: %__MODULE__{
          :DrainSpec => NomadClient.Model.DrainSpec.t() | nil,
          :ForceDeadline => DateTime.t() | nil,
          :StartedAt => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.DrainStrategy do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:DrainSpec, :struct, NomadClient.Model.DrainSpec, options)
  end
end
