# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.EphemeralDisk do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Sticky,
    :Migrate,
    :SizeMB
  ]

  @type t :: %__MODULE__{
          :Sticky => boolean() | nil,
          :Migrate => boolean() | nil,
          :SizeMB => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.EphemeralDisk do
  def decode(value, _options) do
    value
  end
end
