# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.HostDiskStats do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Device,
    :Mountpoint,
    :Size,
    :Used,
    :Available,
    :UsedPercent,
    :InodesUsedPercent
  ]

  @type t :: %__MODULE__{
          :Device => String.t() | nil,
          :Mountpoint => String.t() | nil,
          :Size => integer() | nil,
          :Used => integer() | nil,
          :Available => integer() | nil,
          :UsedPercent => float() | nil,
          :InodesUsedPercent => float() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.HostDiskStats do
  def decode(value, _options) do
    value
  end
end
