# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.Job do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Affinities,
    :AllAtOnce,
    :Constraints,
    :ConsulNamespace,
    :ConsulToken,
    :CreateIndex,
    :Datacenters,
    :DispatchIdempotencyToken,
    :Dispatched,
    :ID,
    :JobModifyIndex,
    :Meta,
    :Migrate,
    :ModifyIndex,
    :Multiregion,
    :Name,
    :Namespace,
    :NomadTokenID,
    :ParameterizedJob,
    :ParentID,
    :Payload,
    :Periodic,
    :Priority,
    :Region,
    :Reschedule,
    :Spreads,
    :Stable,
    :Status,
    :StatusDescription,
    :Stop,
    :SubmitTime,
    :TaskGroups,
    :Type,
    :Update,
    :VaultNamespace,
    :VaultToken,
    :Version
  ]

  @type t :: %__MODULE__{
          :Affinities => [NomadClient.Model.Affinity.t()] | nil,
          :AllAtOnce => boolean() | nil,
          :Constraints => [NomadClient.Model.Constraint.t()] | nil,
          :ConsulNamespace => String.t() | nil,
          :ConsulToken => String.t() | nil,
          :CreateIndex => integer() | nil,
          :Datacenters => [String.t()] | nil,
          :DispatchIdempotencyToken => String.t() | nil,
          :Dispatched => boolean() | nil,
          :ID => String.t() | nil,
          :JobModifyIndex => integer() | nil,
          :Meta => %{optional(String.t()) => String.t()} | nil,
          :Migrate => NomadClient.Model.MigrateStrategy.t() | nil,
          :ModifyIndex => integer() | nil,
          :Multiregion => NomadClient.Model.Multiregion.t() | nil,
          :Name => String.t() | nil,
          :Namespace => String.t() | nil,
          :NomadTokenID => String.t() | nil,
          :ParameterizedJob => NomadClient.Model.ParameterizedJobConfig.t() | nil,
          :ParentID => String.t() | nil,
          :Payload => binary() | nil,
          :Periodic => NomadClient.Model.PeriodicConfig.t() | nil,
          :Priority => integer() | nil,
          :Region => String.t() | nil,
          :Reschedule => NomadClient.Model.ReschedulePolicy.t() | nil,
          :Spreads => [NomadClient.Model.Spread.t()] | nil,
          :Stable => boolean() | nil,
          :Status => String.t() | nil,
          :StatusDescription => String.t() | nil,
          :Stop => boolean() | nil,
          :SubmitTime => integer() | nil,
          :TaskGroups => [NomadClient.Model.TaskGroup.t()] | nil,
          :Type => String.t() | nil,
          :Update => NomadClient.Model.UpdateStrategy.t() | nil,
          :VaultNamespace => String.t() | nil,
          :VaultToken => String.t() | nil,
          :Version => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.Job do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Affinities, :list, NomadClient.Model.Affinity, options)
    |> deserialize(:Constraints, :list, NomadClient.Model.Constraint, options)
    |> deserialize(:Migrate, :struct, NomadClient.Model.MigrateStrategy, options)
    |> deserialize(:Multiregion, :struct, NomadClient.Model.Multiregion, options)
    |> deserialize(:ParameterizedJob, :struct, NomadClient.Model.ParameterizedJobConfig, options)
    |> deserialize(:Periodic, :struct, NomadClient.Model.PeriodicConfig, options)
    |> deserialize(:Reschedule, :struct, NomadClient.Model.ReschedulePolicy, options)
    |> deserialize(:Spreads, :list, NomadClient.Model.Spread, options)
    |> deserialize(:TaskGroups, :list, NomadClient.Model.TaskGroup, options)
    |> deserialize(:Update, :struct, NomadClient.Model.UpdateStrategy, options)
  end
end
