# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobDiff do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Fields,
    :ID,
    :Objects,
    :TaskGroups,
    :Type
  ]

  @type t :: %__MODULE__{
          :Fields => [NomadClient.Model.FieldDiff.t()] | nil,
          :ID => String.t() | nil,
          :Objects => [NomadClient.Model.ObjectDiff.t()] | nil,
          :TaskGroups => [NomadClient.Model.TaskGroupDiff.t()] | nil,
          :Type => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobDiff do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Fields, :list, NomadClient.Model.FieldDiff, options)
    |> deserialize(:Objects, :list, NomadClient.Model.ObjectDiff, options)
    |> deserialize(:TaskGroups, :list, NomadClient.Model.TaskGroupDiff, options)
  end
end
