# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobRevertRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ConsulToken,
    :EnforcePriorVersion,
    :JobID,
    :JobVersion,
    :Namespace,
    :Region,
    :SecretID,
    :VaultToken
  ]

  @type t :: %__MODULE__{
          :ConsulToken => String.t() | nil,
          :EnforcePriorVersion => integer() | nil,
          :JobID => String.t() | nil,
          :JobVersion => integer() | nil,
          :Namespace => String.t() | nil,
          :Region => String.t() | nil,
          :SecretID => String.t() | nil,
          :VaultToken => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobRevertRequest do
  def decode(value, _options) do
    value
  end
end
