# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobChildrenSummary do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Dead,
    :Pending,
    :Running
  ]

  @type t :: %__MODULE__{
          :Dead => integer() | nil,
          :Pending => integer() | nil,
          :Running => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobChildrenSummary do
  def decode(value, _options) do
    value
  end
end
