# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobPlanRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Diff,
    :Job,
    :Namespace,
    :PolicyOverride,
    :Region,
    :SecretID
  ]

  @type t :: %__MODULE__{
          :Diff => boolean() | nil,
          :Job => NomadClient.Model.Job.t() | nil,
          :Namespace => String.t() | nil,
          :PolicyOverride => boolean() | nil,
          :Region => String.t() | nil,
          :SecretID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobPlanRequest do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Job, :struct, NomadClient.Model.Job, options)
  end
end
