# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.JobEvaluateRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :JobID,
    :EvalOptions
  ]

  @type t :: %__MODULE__{
          :JobID => String.t(),
          :EvalOptions => NomadClient.Model.EvalOptions.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobEvaluateRequest do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:EvalOptions, :struct, NomadClient.Model.EvalOptions, options)
  end
end
