# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobSummary do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Children,
    :CreateIndex,
    :JobID,
    :ModifyIndex,
    :Namespace,
    :Summary
  ]

  @type t :: %__MODULE__{
          :Children => NomadClient.Model.JobChildrenSummary.t() | nil,
          :CreateIndex => integer() | nil,
          :JobID => String.t() | nil,
          :ModifyIndex => integer() | nil,
          :Namespace => String.t() | nil,
          :Summary => %{optional(String.t()) => NomadClient.Model.TaskGroupSummary.t()} | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobSummary do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Children, :struct, NomadClient.Model.JobChildrenSummary, options)
    |> deserialize(:Summary, :map, NomadClient.Model.TaskGroupSummary, options)
  end
end
