# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobStabilityRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :JobID,
    :JobVersion,
    :Namespace,
    :Region,
    :SecretID,
    :Stable
  ]

  @type t :: %__MODULE__{
          :JobID => String.t() | nil,
          :JobVersion => integer() | nil,
          :Namespace => String.t() | nil,
          :Region => String.t() | nil,
          :SecretID => String.t() | nil,
          :Stable => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobStabilityRequest do
  def decode(value, _options) do
    value
  end
end
