# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.JobVersionsResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Diffs,
    :KnownLeader,
    :LastContact,
    :LastIndex,
    :NextToken,
    :RequestTime,
    :Versions
  ]

  @type t :: %__MODULE__{
          :Diffs => [NomadClient.Model.JobDiff.t()] | nil,
          :KnownLeader => boolean() | nil,
          :LastContact => integer() | nil,
          :LastIndex => integer() | nil,
          :NextToken => String.t() | nil,
          :RequestTime => integer() | nil,
          :Versions => [NomadClient.Model.Job.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobVersionsResponse do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Diffs, :list, NomadClient.Model.JobDiff, options)
    |> deserialize(:Versions, :list, NomadClient.Model.Job, options)
  end
end
