# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.JobsParseRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :JobHcl,
    :Canonicalize
  ]

  @type t :: %__MODULE__{
          :JobHcl => String.t(),
          :Canonicalize => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.JobsParseRequest do
  def decode(value, _options) do
    value
  end
end
