# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.MigrateStrategy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :HealthCheck,
    :HealthyDeadline,
    :MaxParallel,
    :MinHealthyTime
  ]

  @type t :: %__MODULE__{
          :HealthCheck => String.t() | nil,
          :HealthyDeadline => integer() | nil,
          :MaxParallel => integer() | nil,
          :MinHealthyTime => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.MigrateStrategy do
  def decode(value, _options) do
    value
  end
end
