# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.MultiregionRegion do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Count,
    :Datacenters,
    :Meta,
    :Name
  ]

  @type t :: %__MODULE__{
          :Count => integer() | nil,
          :Datacenters => [String.t()] | nil,
          :Meta => %{optional(String.t()) => String.t()} | nil,
          :Name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.MultiregionRegion do
  def decode(value, _options) do
    value
  end
end
