# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.Multiregion do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Regions,
    :Strategy
  ]

  @type t :: %__MODULE__{
          :Regions => [NomadClient.Model.MultiregionRegion.t()] | nil,
          :Strategy => NomadClient.Model.MultiregionStrategy.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.Multiregion do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Regions, :list, NomadClient.Model.MultiregionRegion, options)
    |> deserialize(:Strategy, :struct, NomadClient.Model.MultiregionStrategy, options)
  end
end
