# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.Namespace do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Capabilities,
    :CreateIndex,
    :Description,
    :Meta,
    :ModifyIndex,
    :Name,
    :Quota
  ]

  @type t :: %__MODULE__{
          :Capabilities => NomadClient.Model.NamespaceCapabilities.t() | nil,
          :CreateIndex => integer() | nil,
          :Description => String.t() | nil,
          :Meta => %{optional(String.t()) => String.t()} | nil,
          :ModifyIndex => integer() | nil,
          :Name => String.t() | nil,
          :Quota => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.Namespace do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Capabilities, :struct, NomadClient.Model.NamespaceCapabilities, options)
  end
end
