# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NetworkResource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CIDR,
    :DNS,
    :Device,
    :DynamicPorts,
    :Hostname,
    :IP,
    :MBits,
    :Mode,
    :ReservedPorts
  ]

  @type t :: %__MODULE__{
          :CIDR => String.t() | nil,
          :DNS => NomadClient.Model.DnsConfig.t() | nil,
          :Device => String.t() | nil,
          :DynamicPorts => [NomadClient.Model.Port.t()] | nil,
          :Hostname => String.t() | nil,
          :IP => String.t() | nil,
          :MBits => integer() | nil,
          :Mode => String.t() | nil,
          :ReservedPorts => [NomadClient.Model.Port.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NetworkResource do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:DNS, :struct, NomadClient.Model.DnsConfig, options)
    |> deserialize(:DynamicPorts, :list, NomadClient.Model.Port, options)
    |> deserialize(:ReservedPorts, :list, NomadClient.Model.Port, options)
  end
end
