# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeListStub do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Address,
    :Attributes,
    :CreateIndex,
    :Datacenter,
    :Drain,
    :Drivers,
    :ID,
    :LastDrain,
    :ModifyIndex,
    :Name,
    :NodeClass,
    :NodeResources,
    :ReservedResources,
    :SchedulingEligibility,
    :Status,
    :StatusDescription,
    :Version
  ]

  @type t :: %__MODULE__{
          :Address => String.t() | nil,
          :Attributes => %{optional(String.t()) => String.t()} | nil,
          :CreateIndex => integer() | nil,
          :Datacenter => String.t() | nil,
          :Drain => boolean() | nil,
          :Drivers => %{optional(String.t()) => NomadClient.Model.DriverInfo.t()} | nil,
          :ID => String.t() | nil,
          :LastDrain => NomadClient.Model.DrainMetadata.t() | nil,
          :ModifyIndex => integer() | nil,
          :Name => String.t() | nil,
          :NodeClass => String.t() | nil,
          :NodeResources => NomadClient.Model.NodeResources.t() | nil,
          :ReservedResources => NomadClient.Model.NodeReservedResources.t() | nil,
          :SchedulingEligibility => String.t() | nil,
          :Status => String.t() | nil,
          :StatusDescription => String.t() | nil,
          :Version => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeListStub do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Drivers, :map, NomadClient.Model.DriverInfo, options)
    |> deserialize(:LastDrain, :struct, NomadClient.Model.DrainMetadata, options)
    |> deserialize(:NodeResources, :struct, NomadClient.Model.NodeResources, options)
    |> deserialize(:ReservedResources, :struct, NomadClient.Model.NodeReservedResources, options)
  end
end
