# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeDeviceResource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Attributes,
    :Instances,
    :Name,
    :Type,
    :Vendor
  ]

  @type t :: %__MODULE__{
          :Attributes => %{optional(String.t()) => NomadClient.Model.Attribute.t()} | nil,
          :Instances => [NomadClient.Model.NodeDevice.t()] | nil,
          :Name => String.t() | nil,
          :Type => String.t() | nil,
          :Vendor => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeDeviceResource do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Attributes, :map, NomadClient.Model.Attribute, options)
    |> deserialize(:Instances, :list, NomadClient.Model.NodeDevice, options)
  end
end
