# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeReservedResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Cpu,
    :Disk,
    :Memory,
    :Networks
  ]

  @type t :: %__MODULE__{
          :Cpu => NomadClient.Model.NodeReservedCpuResources.t() | nil,
          :Disk => NomadClient.Model.NodeReservedDiskResources.t() | nil,
          :Memory => NomadClient.Model.NodeReservedMemoryResources.t() | nil,
          :Networks => NomadClient.Model.NodeReservedNetworkResources.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeReservedResources do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Cpu, :struct, NomadClient.Model.NodeReservedCpuResources, options)
    |> deserialize(:Disk, :struct, NomadClient.Model.NodeReservedDiskResources, options)
    |> deserialize(:Memory, :struct, NomadClient.Model.NodeReservedMemoryResources, options)
    |> deserialize(:Networks, :struct, NomadClient.Model.NodeReservedNetworkResources, options)
  end
end
