# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeUpdateDrainRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DrainSpec,
    :MarkEligible,
    :Meta,
    :NodeID
  ]

  @type t :: %__MODULE__{
          :DrainSpec => NomadClient.Model.DrainSpec.t() | nil,
          :MarkEligible => boolean() | nil,
          :Meta => %{optional(String.t()) => String.t()} | nil,
          :NodeID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeUpdateDrainRequest do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:DrainSpec, :struct, NomadClient.Model.DrainSpec, options)
  end
end
