# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodePurgeResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalCreateIndex,
    :EvalIDs,
    :NodeModifyIndex
  ]

  @type t :: %__MODULE__{
          :EvalCreateIndex => integer() | nil,
          :EvalIDs => [String.t()] | nil,
          :NodeModifyIndex => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodePurgeResponse do
  def decode(value, _options) do
    value
  end
end
