# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeScoreMeta do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeID,
    :NormScore,
    :Scores
  ]

  @type t :: %__MODULE__{
          :NodeID => String.t() | nil,
          :NormScore => float() | nil,
          :Scores => %{optional(String.t()) => float()} | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeScoreMeta do
  def decode(value, _options) do
    value
  end
end
