# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeCpuResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CpuShares,
    :ReservableCpuCores,
    :TotalCpuCores
  ]

  @type t :: %__MODULE__{
          :CpuShares => integer() | nil,
          :ReservableCpuCores => [integer()] | nil,
          :TotalCpuCores => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeCpuResources do
  def decode(value, _options) do
    value
  end
end
