# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeDiskResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DiskMB
  ]

  @type t :: %__MODULE__{
          :DiskMB => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeDiskResources do
  def decode(value, _options) do
    value
  end
end
