# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeReservedNetworkResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ReservedHostPorts
  ]

  @type t :: %__MODULE__{
          :ReservedHostPorts => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeReservedNetworkResources do
  def decode(value, _options) do
    value
  end
end
