# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.NodeResources do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Cpu,
    :Devices,
    :Disk,
    :MaxDynamicPort,
    :Memory,
    :MinDynamicPort,
    :Networks
  ]

  @type t :: %__MODULE__{
          :Cpu => NomadClient.Model.NodeCpuResources.t() | nil,
          :Devices => [NomadClient.Model.NodeDeviceResource.t()] | nil,
          :Disk => NomadClient.Model.NodeDiskResources.t() | nil,
          :MaxDynamicPort => integer() | nil,
          :Memory => NomadClient.Model.NodeMemoryResources.t() | nil,
          :MinDynamicPort => integer() | nil,
          :Networks => [NomadClient.Model.NetworkResource.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.NodeResources do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Cpu, :struct, NomadClient.Model.NodeCpuResources, options)
    |> deserialize(:Devices, :list, NomadClient.Model.NodeDeviceResource, options)
    |> deserialize(:Disk, :struct, NomadClient.Model.NodeDiskResources, options)
    |> deserialize(:Memory, :struct, NomadClient.Model.NodeMemoryResources, options)
    |> deserialize(:Networks, :list, NomadClient.Model.NetworkResource, options)
  end
end
