# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.OneTimeTokenExchangeRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :OneTimeSecretID
  ]

  @type t :: %__MODULE__{
          :OneTimeSecretID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.OneTimeTokenExchangeRequest do
  def decode(value, _options) do
    value
  end
end
