# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.OperatorHealthReply do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Healthy,
    :FailureTolerance,
    :Servers
  ]

  @type t :: %__MODULE__{
          :Healthy => boolean() | nil,
          :FailureTolerance => integer() | nil,
          :Servers => [NomadClient.Model.ServerHealth.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.OperatorHealthReply do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Servers, :list, NomadClient.Model.ServerHealth, options)
  end
end
