# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.PeriodicForceResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalCreateIndex,
    :EvalID,
    :Index
  ]

  @type t :: %__MODULE__{
          :EvalCreateIndex => integer() | nil,
          :EvalID => String.t() | nil,
          :Index => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.PeriodicForceResponse do
  def decode(value, _options) do
    value
  end
end
