# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.PlanAnnotations do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DesiredTGUpdates,
    :PreemptedAllocs
  ]

  @type t :: %__MODULE__{
          :DesiredTGUpdates =>
            %{optional(String.t()) => NomadClient.Model.DesiredUpdates.t()} | nil,
          :PreemptedAllocs => [NomadClient.Model.AllocationListStub.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.PlanAnnotations do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:DesiredTGUpdates, :map, NomadClient.Model.DesiredUpdates, options)
    |> deserialize(:PreemptedAllocs, :list, NomadClient.Model.AllocationListStub, options)
  end
end
