# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.PreemptionConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :SystemSchedulerEnabled,
    :BatchSchedulerEnabled,
    :ServiceSchedulerEnabled
  ]

  @type t :: %__MODULE__{
          :SystemSchedulerEnabled => boolean() | nil,
          :BatchSchedulerEnabled => boolean() | nil,
          :ServiceSchedulerEnabled => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.PreemptionConfig do
  def decode(value, _options) do
    value
  end
end
