# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.QuotaLimit do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Region,
    :RegionLimit,
    :Hash
  ]

  @type t :: %__MODULE__{
          :Region => String.t() | nil,
          :RegionLimit => NomadClient.Model.Resources.t() | nil,
          :Hash => binary() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.QuotaLimit do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:RegionLimit, :struct, NomadClient.Model.Resources, options)
  end
end
