# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.QuotaUsage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Used,
    :CreateIndex,
    :ModifyIndex
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :Used => %{optional(String.t()) => NomadClient.Model.QuotaLimit.t()} | nil,
          :CreateIndex => integer() | nil,
          :ModifyIndex => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.QuotaUsage do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Used, :map, NomadClient.Model.QuotaLimit, options)
  end
end
