# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.QuotaSpec do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CreateIndex,
    :Description,
    :Limits,
    :ModifyIndex,
    :Name
  ]

  @type t :: %__MODULE__{
          :CreateIndex => integer() | nil,
          :Description => String.t() | nil,
          :Limits => [NomadClient.Model.QuotaLimit.t()] | nil,
          :ModifyIndex => integer() | nil,
          :Name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.QuotaSpec do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Limits, :list, NomadClient.Model.QuotaLimit, options)
  end
end
