# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.QuotaSpec do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Description,
    :Limits,
    :CreateIndex,
    :ModifyIndex
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :Description => String.t() | nil,
          :Limits => [NomadClient.Model.QuotaLimit.t()] | nil,
          :CreateIndex => integer() | nil,
          :ModifyIndex => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.QuotaSpec do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Limits, :list, NomadClient.Model.QuotaLimit, options)
  end
end
