# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.QuotaLimit do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Hash,
    :Region,
    :RegionLimit,
    :VariablesLimit
  ]

  @type t :: %__MODULE__{
          :Hash => binary() | nil,
          :Region => String.t() | nil,
          :RegionLimit => NomadClient.Model.Resources.t() | nil,
          :VariablesLimit => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.QuotaLimit do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:RegionLimit, :struct, NomadClient.Model.Resources, options)
  end
end
