# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.RaftConfiguration do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Servers,
    :Index
  ]

  @type t :: %__MODULE__{
          :Servers => [NomadClient.Model.RaftServer.t()] | nil,
          :Index => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.RaftConfiguration do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Servers, :list, NomadClient.Model.RaftServer, options)
  end
end
