# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.RaftConfiguration do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Index,
    :Servers
  ]

  @type t :: %__MODULE__{
          :Index => integer() | nil,
          :Servers => [NomadClient.Model.RaftServer.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.RaftConfiguration do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Servers, :list, NomadClient.Model.RaftServer, options)
  end
end
