# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.RequestedDevice do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Count,
    :Constraints,
    :Affinities
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :Count => integer() | nil,
          :Constraints => [NomadClient.Model.Constraint.t()] | nil,
          :Affinities => [NomadClient.Model.Affinity.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.RequestedDevice do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Constraints, :list, NomadClient.Model.Constraint, options)
    |> deserialize(:Affinities, :list, NomadClient.Model.Affinity, options)
  end
end
