# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.ReschedulePolicy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Attempts,
    :Delay,
    :DelayFunction,
    :Interval,
    :MaxDelay,
    :Unlimited
  ]

  @type t :: %__MODULE__{
          :Attempts => integer() | nil,
          :Delay => integer() | nil,
          :DelayFunction => String.t() | nil,
          :Interval => integer() | nil,
          :MaxDelay => integer() | nil,
          :Unlimited => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ReschedulePolicy do
  def decode(value, _options) do
    value
  end
end
