# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.RescheduleTracker do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Events
  ]

  @type t :: %__MODULE__{
          :Events => [NomadClient.Model.RescheduleEvent.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.RescheduleTracker do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Events, :list, NomadClient.Model.RescheduleEvent, options)
  end
end
