# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.RestartPolicy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Attempts,
    :Delay,
    :Interval,
    :Mode
  ]

  @type t :: %__MODULE__{
          :Attempts => integer() | nil,
          :Delay => integer() | nil,
          :Interval => integer() | nil,
          :Mode => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.RestartPolicy do
  def decode(value, _options) do
    value
  end
end
