# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.ScalingEvent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Count,
    :CreateIndex,
    :Error,
    :EvalID,
    :Message,
    :Meta,
    :PreviousCount,
    :Time
  ]

  @type t :: %__MODULE__{
          :Count => integer() | nil,
          :CreateIndex => integer() | nil,
          :Error => boolean() | nil,
          :EvalID => String.t() | nil,
          :Message => String.t() | nil,
          :Meta => %{optional(String.t()) => any()} | nil,
          :PreviousCount => integer() | nil,
          :Time => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ScalingEvent do
  def decode(value, _options) do
    value
  end
end
