# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.ScalingEvent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Reason,
    :Error,
    :Meta,
    :Time,
    :EvalID
  ]

  @type t :: %__MODULE__{
          :Reason => String.t() | nil,
          :Error => String.t() | nil,
          :Meta => %{optional(String.t()) => map()} | nil,
          :Time => integer() | nil,
          :EvalID => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ScalingEvent do
  def decode(value, _options) do
    value
  end
end
