# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.SchedulerConfiguration do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CreateIndex,
    :MemoryOversubscriptionEnabled,
    :ModifyIndex,
    :PauseEvalBroker,
    :PreemptionConfig,
    :RejectJobRegistration,
    :SchedulerAlgorithm
  ]

  @type t :: %__MODULE__{
          :CreateIndex => integer() | nil,
          :MemoryOversubscriptionEnabled => boolean() | nil,
          :ModifyIndex => integer() | nil,
          :PauseEvalBroker => boolean() | nil,
          :PreemptionConfig => NomadClient.Model.PreemptionConfig.t() | nil,
          :RejectJobRegistration => boolean() | nil,
          :SchedulerAlgorithm => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.SchedulerConfiguration do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:PreemptionConfig, :struct, NomadClient.Model.PreemptionConfig, options)
  end
end
