# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.ServerHealth do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Name,
    :Address,
    :SerfStatus,
    :Version,
    :Leader,
    :LastContact,
    :LastTerm,
    :LastIndex,
    :Healthy,
    :Voter,
    :StableSince
  ]

  @type t :: %__MODULE__{
          :ID => String.t() | nil,
          :Name => String.t() | nil,
          :Address => String.t() | nil,
          :SerfStatus => String.t() | nil,
          :Version => String.t() | nil,
          :Leader => boolean() | nil,
          :LastContact => integer() | nil,
          :LastTerm => integer() | nil,
          :LastIndex => integer() | nil,
          :Healthy => boolean() | nil,
          :Voter => boolean() | nil,
          :StableSince => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.ServerHealth do
  def decode(value, _options) do
    value
  end
end
