# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.SidecarTask do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Config,
    :Driver,
    :Env,
    :KillSignal,
    :KillTimeout,
    :LogConfig,
    :Meta,
    :Name,
    :Resources,
    :ShutdownDelay,
    :User
  ]

  @type t :: %__MODULE__{
          :Config => %{optional(String.t()) => any()} | nil,
          :Driver => String.t() | nil,
          :Env => %{optional(String.t()) => String.t()} | nil,
          :KillSignal => String.t() | nil,
          :KillTimeout => integer() | nil,
          :LogConfig => NomadClient.Model.LogConfig.t() | nil,
          :Meta => %{optional(String.t()) => String.t()} | nil,
          :Name => String.t() | nil,
          :Resources => NomadClient.Model.Resources.t() | nil,
          :ShutdownDelay => integer() | nil,
          :User => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.SidecarTask do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:LogConfig, :struct, NomadClient.Model.LogConfig, options)
    |> deserialize(:Resources, :struct, NomadClient.Model.Resources, options)
  end
end
