# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.Spread do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Attribute,
    :Weight,
    :SpreadTarget
  ]

  @type t :: %__MODULE__{
          :Attribute => String.t() | nil,
          :Weight => integer() | nil,
          :SpreadTarget => [NomadClient.Model.SpreadTarget.t()] | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.Spread do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:SpreadTarget, :list, NomadClient.Model.SpreadTarget, options)
  end
end
