# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.SpreadTarget do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Percent,
    :Value
  ]

  @type t :: %__MODULE__{
          :Percent => integer() | nil,
          :Value => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.SpreadTarget do
  def decode(value, _options) do
    value
  end
end
