# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.TaskDiff do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Annotations,
    :Fields,
    :Name,
    :Objects,
    :Type
  ]

  @type t :: %__MODULE__{
          :Annotations => [String.t()] | nil,
          :Fields => [NomadClient.Model.FieldDiff.t()] | nil,
          :Name => String.t() | nil,
          :Objects => [NomadClient.Model.ObjectDiff.t()] | nil,
          :Type => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.TaskDiff do
  import NomadClient.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Fields, :list, NomadClient.Model.FieldDiff, options)
    |> deserialize(:Objects, :list, NomadClient.Model.ObjectDiff, options)
  end
end
