# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.TaskHandle do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DriverState,
    :Version
  ]

  @type t :: %__MODULE__{
          :DriverState => binary() | nil,
          :Version => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.TaskHandle do
  def decode(value, _options) do
    value
  end
end
