# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.TaskGroupSummary do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Complete,
    :Failed,
    :Lost,
    :Queued,
    :Running,
    :Starting,
    :Unknown
  ]

  @type t :: %__MODULE__{
          :Complete => integer() | nil,
          :Failed => integer() | nil,
          :Lost => integer() | nil,
          :Queued => integer() | nil,
          :Running => integer() | nil,
          :Starting => integer() | nil,
          :Unknown => integer() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.TaskGroupSummary do
  def decode(value, _options) do
    value
  end
end
