# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.TaskLifecycle do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Hook,
    :Sidecar
  ]

  @type t :: %__MODULE__{
          :Hook => String.t() | nil,
          :Sidecar => boolean() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.TaskLifecycle do
  def decode(value, _options) do
    value
  end
end
