# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.TaskArtifact do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :GetterHeaders,
    :GetterMode,
    :GetterOptions,
    :GetterSource,
    :RelativeDest
  ]

  @type t :: %__MODULE__{
          :GetterHeaders => %{optional(String.t()) => String.t()} | nil,
          :GetterMode => String.t() | nil,
          :GetterOptions => %{optional(String.t()) => String.t()} | nil,
          :GetterSource => String.t() | nil,
          :RelativeDest => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.TaskArtifact do
  def decode(value, _options) do
    value
  end
end
