# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.Vault do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Policies,
    :Env,
    :ChangeMode,
    :ChangeSignal
  ]

  @type t :: %__MODULE__{
          :Policies => [String.t()] | nil,
          :Env => boolean() | nil,
          :ChangeMode => String.t() | nil,
          :ChangeSignal => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.Vault do
  def decode(value, _options) do
    value
  end
end
