# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule NomadClient.Model.VolumeMount do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Volume,
    :Destination,
    :ReadOnly,
    :PropagationMode
  ]

  @type t :: %__MODULE__{
          :Volume => String.t() | nil,
          :Destination => String.t() | nil,
          :ReadOnly => boolean() | nil,
          :PropagationMode => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.VolumeMount do
  def decode(value, _options) do
    value
  end
end
