# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Model.VolumeMount do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Destination,
    :PropagationMode,
    :ReadOnly,
    :Volume
  ]

  @type t :: %__MODULE__{
          :Destination => String.t() | nil,
          :PropagationMode => String.t() | nil,
          :ReadOnly => boolean() | nil,
          :Volume => String.t() | nil
        }
end

defimpl Poison.Decoder, for: NomadClient.Model.VolumeMount do
  def decode(value, _options) do
    value
  end
end
