# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.AclTokenListStub do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :AccessorID,
    :Name,
    :Type,
    :Policies,
    :Global,
    :CreateTime,
    :CreateIndex,
    :ModifyIndex
  ]

  @type t :: %__MODULE__{
          :AccessorID => String.t() | nil,
          :Name => String.t() | nil,
          :Type => String.t() | nil,
          :Policies => [String.t()] | nil,
          :Global => boolean() | nil,
          :CreateTime => DateTime.t() | nil,
          :CreateIndex => integer() | nil,
          :ModifyIndex => integer() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.AclTokenListStub do
  def decode(value, _options) do
    value
  end
end
