# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.Attribute do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Float",
    :"Int",
    :"String",
    :"Bool",
    :"Unit"
  ]

  @type t :: %__MODULE__{
    :"Float" => float() | nil,
    :"Int" => integer() | nil,
    :"String" => String.t | nil,
    :"Bool" => boolean() | nil,
    :"Unit" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Attribute do
  def decode(value, _options) do
    value
  end
end

