# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.CheckRestart do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Limit",
    :"Grace",
    :"IgnoreWarnings"
  ]

  @type t :: %__MODULE__{
    :"Limit" => integer() | nil,
    :"Grace" => integer() | nil,
    :"IgnoreWarnings" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CheckRestart do
  def decode(value, _options) do
    value
  end
end

