# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ConsulUpstream do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DestinationName",
    :"LocalBindPort"
  ]

  @type t :: %__MODULE__{
    :"DestinationName" => String.t | nil,
    :"LocalBindPort" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulUpstream do
  def decode(value, _options) do
    value
  end
end

