# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.CsiPluginListStub do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ID",
    :"Provider",
    :"ControllerRequired",
    :"ControllersHealthy",
    :"ControllersExpected",
    :"NodesHealthy",
    :"NodesExpected",
    :"CreateIndex",
    :"ModifyIndex"
  ]

  @type t :: %__MODULE__{
    :"ID" => String.t | nil,
    :"Provider" => String.t | nil,
    :"ControllerRequired" => boolean() | nil,
    :"ControllersHealthy" => integer() | nil,
    :"ControllersExpected" => integer() | nil,
    :"NodesHealthy" => integer() | nil,
    :"NodesExpected" => integer() | nil,
    :"CreateIndex" => integer() | nil,
    :"ModifyIndex" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiPluginListStub do
  def decode(value, _options) do
    value
  end
end

