# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.CsiTopology do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Segments"
  ]

  @type t :: %__MODULE__{
    :"Segments" => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiTopology do
  def decode(value, _options) do
    value
  end
end

