# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.DesiredTransition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Migrate",
    :"Reschedule"
  ]

  @type t :: %__MODULE__{
    :"Migrate" => boolean() | nil,
    :"Reschedule" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DesiredTransition do
  def decode(value, _options) do
    value
  end
end

