# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.DeviceStats do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Summary,
    :Stats,
    :Timestamp
  ]

  @type t :: %__MODULE__{
          :Summary => Nomad.Model.StatValue.t() | nil,
          :Stats => Nomad.Model.StatObject.t() | nil,
          :Timestamp => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.DeviceStats do
  import Nomad.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Summary, :struct, Nomad.Model.StatValue, options)
    |> deserialize(:Stats, :struct, Nomad.Model.StatObject, options)
  end
end
