# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.DriverInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Attributes",
    :"Detected",
    :"Healthy",
    :"HealthDescription",
    :"UpdateTime"
  ]

  @type t :: %__MODULE__{
    :"Attributes" => %{optional(String.t) => String.t} | nil,
    :"Detected" => boolean() | nil,
    :"Healthy" => boolean() | nil,
    :"HealthDescription" => String.t | nil,
    :"UpdateTime" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DriverInfo do
  def decode(value, _options) do
    value
  end
end

