# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.HostMemoryStats do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Total",
    :"Available",
    :"Used",
    :"Free"
  ]

  @type t :: %__MODULE__{
    :"Total" => integer() | nil,
    :"Available" => integer() | nil,
    :"Used" => integer() | nil,
    :"Free" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.HostMemoryStats do
  def decode(value, _options) do
    value
  end
end

