# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.HostCpuStats do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CPU",
    :"User",
    :"System",
    :"Idle"
  ]

  @type t :: %__MODULE__{
    :"CPU" => String.t | nil,
    :"User" => float() | nil,
    :"System" => float() | nil,
    :"Idle" => float() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.HostCpuStats do
  def decode(value, _options) do
    value
  end
end

