# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobDeregisterResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalID,
    :EvalCreateIndex,
    :JobModifyIndex,
    :Warnings
  ]

  @type t :: %__MODULE__{
          :EvalID => String.t() | nil,
          :EvalCreateIndex => integer() | nil,
          :JobModifyIndex => integer() | nil,
          :Warnings => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.JobDeregisterResponse do
  def decode(value, _options) do
    value
  end
end
