# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobVersionsResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Versions,
    :Diffs
  ]

  @type t :: %__MODULE__{
          :Versions => [Nomad.Model.Job.t()] | nil,
          :Diffs => [Nomad.Model.JobDiff.t()] | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.JobVersionsResponse do
  import Nomad.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Versions, :list, Nomad.Model.Job, options)
    |> deserialize(:Diffs, :list, Nomad.Model.JobDiff, options)
  end
end
