# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobStabilityRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobID",
    :"JobVersion",
    :"Stable"
  ]

  @type t :: %__MODULE__{
    :"JobID" => String.t,
    :"JobVersion" => integer() | nil,
    :"Stable" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobStabilityRequest do
  def decode(value, _options) do
    value
  end
end

