# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JoinResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"error",
    :"num_joined"
  ]

  @type t :: %__MODULE__{
    :"error" => String.t | nil,
    :"num_joined" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JoinResponse do
  def decode(value, _options) do
    value
  end
end

