# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.LogConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :MaxFiles,
    :MaxFileSizeMB
  ]

  @type t :: %__MODULE__{
          :MaxFiles => integer() | nil,
          :MaxFileSizeMB => integer() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.LogConfig do
  def decode(value, _options) do
    value
  end
end
