# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.MemoryStats do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Rss",
    :"Cache",
    :"Swap",
    :"Usage",
    :"MaxUsage",
    :"KernelUsage",
    :"KernelMaxUsage",
    :"Measured"
  ]

  @type t :: %__MODULE__{
    :"Rss" => integer() | nil,
    :"Cache" => integer() | nil,
    :"Swap" => integer() | nil,
    :"Usage" => integer() | nil,
    :"MaxUsage" => integer() | nil,
    :"KernelUsage" => integer() | nil,
    :"KernelMaxUsage" => integer() | nil,
    :"Measured" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.MemoryStats do
  def decode(value, _options) do
    value
  end
end

