# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.MonitorMessage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Level",
    :"Message"
  ]

  @type t :: %__MODULE__{
    :"Level" => integer() | nil,
    :"Message" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.MonitorMessage do
  def decode(value, _options) do
    value
  end
end

