# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.NetworkResource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Mode,
    :Device,
    :CIDR,
    :IP,
    :MBits,
    :ReservedPorts,
    :DynamicPorts,
    :DNS
  ]

  @type t :: %__MODULE__{
          :Mode => String.t() | nil,
          :Device => String.t() | nil,
          :CIDR => String.t() | nil,
          :IP => String.t() | nil,
          :MBits => integer() | nil,
          :ReservedPorts => [Nomad.Model.Port.t()] | nil,
          :DynamicPorts => [Nomad.Model.Port.t()] | nil,
          :DNS => Nomad.Model.NetworkDns.t() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.NetworkResource do
  import Nomad.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:ReservedPorts, :list, Nomad.Model.Port, options)
    |> deserialize(:DynamicPorts, :list, Nomad.Model.Port, options)
    |> deserialize(:DNS, :struct, Nomad.Model.NetworkDns, options)
  end
end
