# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.NodeEligibilityUpdateResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeModifyIndex,
    :EvalIDs,
    :EvalCreateIndex
  ]

  @type t :: %__MODULE__{
          :NodeModifyIndex => integer() | nil,
          :EvalIDs => [String.t()] | nil,
          :EvalCreateIndex => integer() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeEligibilityUpdateResponse do
  def decode(value, _options) do
    value
  end
end
