# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.NodeScoreMeta do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeID,
    :Scores,
    :NormScore
  ]

  @type t :: %__MODULE__{
          :NodeID => String.t() | nil,
          :Scores => %{optional(String.t()) => Nomad.Model.Float.t()} | nil,
          :NormScore => float() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeScoreMeta do
  def decode(value, _options) do
    value
  end
end
