# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.NodeDevice do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ID",
    :"Healthy",
    :"HealthDescription",
    :"Locality"
  ]

  @type t :: %__MODULE__{
    :"ID" => String.t | nil,
    :"Healthy" => boolean() | nil,
    :"HealthDescription" => String.t | nil,
    :"Locality" => Nomad.Model.NodeDeviceLocality.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeDevice do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Locality", :struct, Nomad.Model.NodeDeviceLocality, options)
  end
end

