# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ParameterizedJobConfig do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Payload,
    :MetaRequired,
    :MetaOptional
  ]

  @type t :: %__MODULE__{
          :Payload => String.t() | nil,
          :MetaRequired => [String.t()] | nil,
          :MetaOptional => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.ParameterizedJobConfig do
  def decode(value, _options) do
    value
  end
end
