# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.PeriodicForceResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"EvalID"
  ]

  @type t :: %__MODULE__{
    :"EvalID" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.PeriodicForceResponse do
  def decode(value, _options) do
    value
  end
end

