# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.QuotaUsage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Used",
    :"CreateIndex",
    :"ModifyIndex"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t | nil,
    :"Used" => %{optional(String.t) => Nomad.Model.QuotaLimit.t} | nil,
    :"CreateIndex" => integer() | nil,
    :"ModifyIndex" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.QuotaUsage do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Used", :map, Nomad.Model.QuotaLimit, options)
  end
end

