# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.RescheduleTracker do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Events"
  ]

  @type t :: %__MODULE__{
    :"Events" => [Nomad.Model.RescheduleEvent.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.RescheduleTracker do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Events", :list, Nomad.Model.RescheduleEvent, options)
  end
end

