# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.RestartPolicy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Interval,
    :Attempts,
    :Delay,
    :Mode
  ]

  @type t :: %__MODULE__{
          :Interval => integer() | nil,
          :Attempts => integer() | nil,
          :Delay => integer() | nil,
          :Mode => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.RestartPolicy do
  def decode(value, _options) do
    value
  end
end
