# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.SchedulerConfigurationResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :SchedulerConfig
  ]

  @type t :: %__MODULE__{
          :SchedulerConfig => Nomad.Model.SchedulerConfiguration.t() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.SchedulerConfigurationResponse do
  import Nomad.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:SchedulerConfig, :struct, Nomad.Model.SchedulerConfiguration, options)
  end
end
