# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.SentinelPolicyListStub do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Description",
    :"Scope",
    :"EnforcementLevel",
    :"CreateIndex",
    :"ModifyIndex"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t | nil,
    :"Description" => String.t | nil,
    :"Scope" => String.t | nil,
    :"EnforcementLevel" => String.t | nil,
    :"CreateIndex" => integer() | nil,
    :"ModifyIndex" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SentinelPolicyListStub do
  def decode(value, _options) do
    value
  end
end

