# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.SidecarTask do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Driver,
    :User,
    :Config,
    :Env,
    :Resources,
    :Meta,
    :KillTimeout,
    :LogConfig,
    :ShutdownDelay,
    :KillSignal
  ]

  @type t :: %__MODULE__{
          :Name => String.t() | nil,
          :Driver => String.t() | nil,
          :User => String.t() | nil,
          :Config => %{optional(String.t()) => map()} | nil,
          :Env => %{optional(String.t()) => String.t()} | nil,
          :Resources => Nomad.Model.Resources.t() | nil,
          :Meta => %{optional(String.t()) => String.t()} | nil,
          :KillTimeout => integer() | nil,
          :LogConfig => Nomad.Model.LogConfig.t() | nil,
          :ShutdownDelay => integer() | nil,
          :KillSignal => String.t() | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.SidecarTask do
  import Nomad.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Resources, :struct, Nomad.Model.Resources, options)
    |> deserialize(:LogConfig, :struct, Nomad.Model.LogConfig, options)
  end
end
