# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.StreamFrame do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Offset",
    :"Data",
    :"File",
    :"FileEvent"
  ]

  @type t :: %__MODULE__{
    :"Offset" => integer() | nil,
    :"Data" => binary() | nil,
    :"File" => String.t | nil,
    :"FileEvent" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.StreamFrame do
  def decode(value, _options) do
    value
  end
end

