# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.TaskDiff do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Name,
    :Fields,
    :Objects,
    :Annotations
  ]

  @type t :: %__MODULE__{
          :Type => String.t() | nil,
          :Name => String.t() | nil,
          :Fields => [Nomad.Model.FieldDiff.t()] | nil,
          :Objects => [Nomad.Model.ObjectDiff.t()] | nil,
          :Annotations => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: Nomad.Model.TaskDiff do
  import Nomad.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:Fields, :list, Nomad.Model.FieldDiff, options)
    |> deserialize(:Objects, :list, Nomad.Model.ObjectDiff, options)
  end
end
