# NOTE: This file is auto generated by OpenAPI Generator 6.2.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule NomadClient.Api.Regions do
  @moduledoc """
  API calls for all endpoints tagged `Regions`.
  """

  alias NomadClient.Connection
  import NomadClient.RequestBuilder

  @doc """

  ### Parameters

  - `connection` (NomadClient.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%String{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_regions(Tesla.Env.client(), keyword()) ::
          {:ok, nil} | {:ok, list(String.t())} | {:error, Tesla.Env.t()}
  def get_regions(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/regions")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, []},
      {400, false},
      {403, false},
      {405, false},
      {500, false}
    ])
  end
end
